//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to افزودن کالا.
        /// </summary>
        internal static string AddProduct
        {
            get
            {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to افزودن کالا به سبد خرید .
        /// </summary>
        internal static string AddProduct2Basket
        {
            get
            {
                return ResourceManager.GetString("AddProduct2Basket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to افزودن به لیست کالاهای موجود.
        /// </summary>
        internal static string AddProduct2Db
        {
            get
            {
                return ResourceManager.GetString("AddProduct2Db", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کالا با موفقیت به دیتابیس اضافه شد.
        /// </summary>
        internal static string AddProuct2DbSuccess
        {
            get
            {
                return ResourceManager.GetString("AddProuct2DbSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        internal static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ثبت تغییرات.
        /// </summary>
        internal static string ApplyChange
        {
            get
            {
                return ResourceManager.GetString("ApplyChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ایران-تهران-خیابان ولنجک-دانشگاه شهید بهشتی-دانشکده علوم و مهندسی کامپیوتر.
        /// </summary>
        internal static string BeheshTAddress
        {
            get
            {
                return ResourceManager.GetString("BeheshTAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خرید کالا.
        /// </summary>
        internal static string BuyProduct
        {
            get
            {
                return ResourceManager.GetString("BuyProduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        internal static string ContactUs
        {
            get
            {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        internal static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to موجودی را به صورت عددی وارد نمایید.
        /// </summary>
        internal static string ErrorAmountNumber
        {
            get
            {
                return ResourceManager.GetString("ErrorAmountNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کالای مورد نظر یافت نشد.
        /// </summary>
        internal static string ErrorItemNotFound
        {
            get
            {
                return ResourceManager.GetString("ErrorItemNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عدم موجودی.
        /// </summary>
        internal static string ErrorNoItems
        {
            get
            {
                return ResourceManager.GetString("ErrorNoItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to قیمت را به صورت عددی وارد نمایید.
        /// </summary>
        internal static string ErrorPriceNumber
        {
            get
            {
                return ResourceManager.GetString("ErrorPriceNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عکس پیش نمایش کالا را انتخاب نمایید.
        /// </summary>
        internal static string ErrorPrivewImage
        {
            get
            {
                return ResourceManager.GetString("ErrorPrivewImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عکس پیش نمایش کالا را به فرمت jpg انتخاب نمایید.
        /// </summary>
        internal static string ErrorPrivewImageFormat
        {
            get
            {
                return ResourceManager.GetString("ErrorPrivewImageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تعداد کالای موجود.
        /// </summary>
        internal static string ItemsCnt
        {
            get
            {
                return ResourceManager.GetString("ItemsCnt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        internal static string LogIn
        {
            get
            {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string LogOut
        {
            get
            {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        internal static string MainPage
        {
            get
            {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شماره های تماس اصلی.
        /// </summary>
        internal static string MainPhone
        {
            get
            {
                return ResourceManager.GetString("MainPhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مدیریت پروفایل کاربری.
        /// </summary>
        internal static string ManageProfile
        {
            get
            {
                return ResourceManager.GetString("ManageProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بخش بازاریابی و فروش.
        /// </summary>
        internal static string Marketing
        {
            get
            {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        internal static string MobilePhone
        {
            get
            {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اگر ثبت نام نکرده اید.
        /// </summary>
        internal static string NotRegistered
        {
            get
            {
                return ResourceManager.GetString("NotRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        internal static string PassWord
        {
            get
            {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شماره های تماس.
        /// </summary>
        internal static string PhoneNumbers
        {
            get
            {
                return ResourceManager.GetString("PhoneNumbers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to محبوب ترین کالاها.
        /// </summary>
        internal static string PopProducts
        {
            get
            {
                return ResourceManager.GetString("PopProducts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ریال.
        /// </summary>
        internal static string PriceUnit
        {
            get
            {
                return ResourceManager.GetString("PriceUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to محصول.
        /// </summary>
        internal static string Product
        {
            get
            {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کدکالا.
        /// </summary>
        internal static string ProductId
        {
            get
            {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to توضیحات کالا.
        /// </summary>
        internal static string ProductInfo
        {
            get
            {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نام کالا.
        /// </summary>
        internal static string ProductName
        {
            get
            {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to پیش نمایش.
        /// </summary>
        internal static string ProductPreview
        {
            get
            {
                return ResourceManager.GetString("ProductPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to قیمت.
        /// </summary>
        internal static string ProductPrice
        {
            get
            {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کالا با موفقیت به سبد خرید افزوده شد.
        /// </summary>
        internal static string ProductSuccessAdd2Basket
        {
            get
            {
                return ResourceManager.GetString("ProductSuccessAdd2Basket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        internal static string Register
        {
            get
            {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مرا بخاطر بسپار.
        /// </summary>
        internal static string RememberMe
        {
            get
            {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  تعداد کالای درخواستی.
        /// </summary>
        internal static string RequestCnt
        {
            get
            {
                return ResourceManager.GetString("RequestCnt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to جست و جو.
        /// </summary>
        internal static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to جست و جو در فروشگاه.
        /// </summary>
        internal static string SearchIn
        {
            get
            {
                return ResourceManager.GetString("SearchIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to فروشگاه اینترنتی شیوا.
        /// </summary>
        internal static string ShivaOnlineShop
        {
            get
            {
                return ResourceManager.GetString("ShivaOnlineShop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی.
        /// </summary>
        internal static string Support
        {
            get
            {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to جمع صورت حساب.
        /// </summary>
        internal static string TotalBill
        {
            get
            {
                return ResourceManager.GetString("TotalBill", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        internal static string Username
        {
            get
            {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خوش آمدید.
        /// </summary>
        internal static string Welcome
        {
            get
            {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to به صفحه ارتباط با ما خوش آمدید.
        /// </summary>
        internal static string Welcome2ContactUs
        {
            get
            {
                return ResourceManager.GetString("Welcome2ContactUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to به فروشگاه اینترنتی شیوا خوش آمدید.
        /// </summary>
        internal static string Welcome2ShivaOnlineShop
        {
            get
            {
                return ResourceManager.GetString("Welcome2ShivaOnlineShop", resourceCulture);
            }
        }

        public static string UrUsernameAddSuccessfully { get; set; }

        public static string CantRegisterRightNow { get; set; }

        public static string ErrorRepeatMobile { get; set; }

        public static string ErrorRepeatEmail { get; set; }

        public static string ErrorRepeatUsername { get; set; }

        public static string ErrorValidMobile { get; set; }

        public static string ErrorValidEmail { get; set; }

        public static string ErrorValidEmailField { get; set; }

        public static string ErrorShortPass { get; set; }

        public static string ErrorCompleteForm { get; set; }
    }
}
