//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید کالا.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن به سبد خرید کالا.
        /// </summary>
        internal static string AddProduct2Basket {
            get {
                return ResourceManager.GetString("AddProduct2Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن به لیست کالاهای موجود.
        /// </summary>
        internal static string AddProduct2Db {
            get {
                return ResourceManager.GetString("AddProduct2Db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا با موفقیت اضافه شد.
        /// </summary>
        internal static string AddProuct2DbSuccess {
            get {
                return ResourceManager.GetString("AddProuct2DbSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید کالا.
        /// </summary>
        internal static string BuyProduct {
            get {
                return ResourceManager.GetString("BuyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی را به صورت عددی وارد نمایید.
        /// </summary>
        internal static string ErrorAmountNumber {
            get {
                return ResourceManager.GetString("ErrorAmountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم موجودی.
        /// </summary>
        internal static string ErrorNoItems {
            get {
                return ResourceManager.GetString("ErrorNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت را به صورت عددی وارد نمایید.
        /// </summary>
        internal static string ErrorPriceNumber {
            get {
                return ResourceManager.GetString("ErrorPriceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس پیش نمایش کالا را انتخاب نمایید.
        /// </summary>
        internal static string ErrorPrivewImage {
            get {
                return ResourceManager.GetString("ErrorPrivewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس پیش نمایش کالا را به فرمت jpg انتخاب نمایید.
        /// </summary>
        internal static string ErrorPrivewImageFormat {
            get {
                return ResourceManager.GetString("ErrorPrivewImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد.
        /// </summary>
        internal static string ItemsCnt {
            get {
                return ResourceManager.GetString("ItemsCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تومان.
        /// </summary>
        internal static string PriceUnit {
            get {
                return ResourceManager.GetString("PriceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدکالا.
        /// </summary>
        internal static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کالا.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نمایش.
        /// </summary>
        internal static string ProductPreview {
            get {
                return ResourceManager.GetString("ProductPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش آمدید.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
